# Generated by Django 3.1.2 on 2021-02-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=40)),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=40)),
                ('tz', models.CharField(max_length=40)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
